### ISSUE TITLE
coverage:compile errors with package objects (sbt 0.11.x scala 2.9.1 )

### ISSUE THREAD

**Issue by jestan** [mtkopone/scct#20]
I am using scct with sbt-scct plugin(https://github.com/dvc94ch/sbt-scct, sbt 0.11.2 scala 2.9.1) and getting compile errors in 'sbt coverage:compile' for use of classes inside a package object , but 'sbt compile' completes without any compile errors.

```
Below sample code explains what I am trying to do.

 //in file com/xyz/x1/common.scala

 package com.xyz.x1

 package object common {
   case class Person()
 }


 //somewhere in the code base

 import com.xyz.x1.common._

 object myRequestVar extends RequestVar[Person](Person())



 //sbt coverage:compile error output

 [error]  found   : com.xyz.x1.package.com.xyz.x1.Person
 [error]  required: com.xyz.x1.package.(some other)com.xyz.x1.Person
 [error]  object myRequestVar extends RequestVar[Person](Person())
```

is it something to do with scct compiler plugin or in sbt 0.11.2 ?

same result with https://github.com/quelgar/sbt-scct/

**Comment by mtkopone** [comment]
Hi,

This looks very untrivial.

Turns out it is somehow specific to sbt 0.10.x and 0.11.x. A simple test project with this code compiles fine with sbt 0.7.7 and with maven 3.0.3 and stand-alone. With or without scct instrumentation.

With either of the sbt-scct plugins for sbt > 0.7.7, it fails with that error.

"Downgrading" either the package object to a regular object 
or the case class to a regular class makes the error disappear.

You may have run into some very obscure ground here, since the "case class in package object" is causing weirdness in even the compiler internals, see: http://www.scala-lang.org/node/10482

There's really very little I can do to help right now. 
Maybe the people maintaining the more recent sbt-plugins could help?

Sorry,

**Comment by jestan** [comment]
Thanks for the reply,

After moving case classes out of the package object, it works :)

**Comment by retronym** [comment]
See: https://github.com/scala/scala/pull/3389
