### ISSUE TITLE
Request: Scala 2.10-RC1 build

### ISSUE THREAD

**Issue by dlouwers** [mtkopone/scct#33]
Naturally SBT cannot find a build for Scala 2.10. Tried using:

addSbtPlugin("reaktor" % "sbt-scct" % "0.2-SNAPSHOT" from "http://mtkopone.github.com/scct/maven-repo/reaktor/sbt-scct_2.9.2_0.12/0.2-SNAPSHOT")

This seems to work but including the settings doesn't. 

error: not found: value ScctPlugin seq(ScctPlugin.instrumentSettings : _*)

Any help would be appreciated.

**Comment by jphautin** [comment]
+1

**Comment by mtkopone** [comment]
(Oh man, I was sure I had answered this earlier... Sorry for the delay.)

Just compiling scct against 2.10 failed completely. So this needs some work.

Turns out quite a lot has changed btw 2.9 and 2.10. Among other things, new phases exist in the compiler prior to scct's. This means that to be able to figure out what to instrument, scct probably needs to be moved up in the phase list. That might not be a trivial job.

When I previously followed a RC of scala, I ended up having to rewrite all the changes once the release came out. Mostly because of changes to the compiler. So I'm treading carefully on this one.

**Comment by atooni** [comment]
First of all, thanks for your work on this. I have used SCCT on a sample project with 2.9 successfully and have now found your remarks here. I am willing to put some work into this, but would probably need a pointer where to start looking. 

I have forked your repository and have added a pom file for a maven based build. I have done this mainly because I am uing Idea and for some reason Scala 2.10 seems not to work well with sbt. Perhaps thats just me not understanding SBT enough. 

I am able to build SCCT with 2.10.0-RC3 and also the tests seem to succeed. Applying SCCT to my own project fails. 

Do you have any pointers to understand SCCT inner workings better ? 

Best regards 
Andreas

**Comment by mtkopone** [comment]
I've had time to look a little bit into this.

A couple of changes we're required to make scct build itself with 2.10. But then the reports were nonsense, as so much code is now being changed and generated by the compiler before the plugin sees the source.

Looks like moving the plugin before the patmat phase might help. But there are then some syntax trees that fail to instrument correctly (at least match-cases). I'm looking into those problems now.

I don't really have any general pointers, if you have a specific problem I can probably help better.

Cheers, and thanks for the input,

**Comment by mtkopone** [comment]
2.10.0-RC3 and (hopefully) upward should now work.

Just change your scalaVersion to "2.10.0-RC3", and the new scct binaries should get picked up.

Testing of the 2.10 version was quite limited, so please let me know of any problems
