### ISSUE TITLE
test-coverage hangs on Windows

### ISSUE THREAD

**Issue by etorreborre** [mtkopone/scct#6]
When trying to generate the coverage for my new (unreleased) specs2 library, the process hangs. Then when I ctrl-C the process, it generates all the files at the root of the project with partial totals for the coverage. 

You can access a snapshot of the library here: http://specs.googlecode.com/svn/docs/specs2.zip

**Comment by mtkopone** [comment]
Hi, 

Turns out this is a bit tricky. The main reason is that the SpecsFramework class is being used in sbt's main classloader. That class is from the project's source tree, and therefore instrumented. It causes scct to initialise itself in both that classloader and the one being used to run the tests. 

I'm looking into how to solve it.

**Comment by mtkopone** [comment]
This should be fixed now.

However: Any calls to instrumented classes before the actual test run starts are ignored in coverage analysis. So in this case, SpecsFramework and such will report zero coverage, as they are only used by the sbt-side, not in any test case.

Let me know how it's working for you.

**Comment by etorreborre** [comment]
I'll give it a try this week. Thanks!
