### ISSUE TITLE
Multi-module support

### ISSUE THREAD

**Issue by ijuma** [mtkopone/scct#7]
I think it would be nice if there was a way to run the tool in a multi-module project so that the coverage was computed for all the tests in all the modules instead of a per module basis. This would allow one to check the test coverage including integration tests, which is also useful.

**Comment by mtkopone** [comment]
Yep, that would be nice. 

multi-module support is currently "in the backlog", but the time I have for working with scct is very limited at the moment.

**Comment by mtkopone** [comment]
scct 0.2-SNAPSHOT works **with** multi-module projects using both sbt and maven. 

However, it is only capable of creating and merging per-child-project reports, so "inter-project" coverage and instrumentation still doesn't work. "inter-project" in this case meaning keeping track of coverage for code that is tested from another child-project. Looks like implementing that is going to be another build-system-nightmare.

I'm still gonna close this issue, since the basics are done and scct can be used in multi-module environments. 
Feel free to open another one regarding "inter-project" coverage if that is what you primarily meant.

**Comment by ijuma** [comment]
Great, thanks! When is scct 0.2 expected to be released? To answer your question, "inter-project" would be nice, but I will first test what's there before submitting another issue.

**Comment by mtkopone** [comment]
It's out. The instructions at http://mtkopone.github.com/scct have been updated to work with the latest version.

**Comment by b0c1** [comment]
Hi. You planned to merge the cobertura.xml file too? (ex: file location prefixed from parent root not from project root)
Because the jenkins cobertura plugin can't open the source file.
